# To execute this docker compose yml file use `docker compose -f docker-compose-v2.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v2.yml down`
services:
  chrome:
    image: selenium/node-chrome:4.39.0-20251212
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.39.0-20251212
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.39.0-20251212
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.39.0-20251212
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  test-server:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    environment:
      - TEST_MODE=true
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 5s
      timeout: 10s
      retries: 5
  behave-tests:
      build:
        context: .
        target: test
      depends_on:
        test-server:
          condition: service_healthy
        selenium-hub:
          condition: service_healthy
        chrome:
          condition: service_started
        firefox:
          condition: service_started
      environment:
        - TEST_MODE=true
        - HEADLESS=true
        - SELENIUM_URL=http://selenium-hub:4444/wd/hub
        - BASE_URL=http://test-server:5000
        - BROWSER_TYPE=chrome
